# Generated by Django 3.2.16 on 2022-10-22 17:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('R', 'Rock'), ('J', 'Jazz'), ('P', 'Pop'), ('H', 'House'), ('B', 'Blues'), ('M', 'Metal')], max_length=1)),
                ('other', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='surname',
            new_name='artist_surname',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50, unique=True)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('song_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='streaming_music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateField()),
                ('album_image', cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image')),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artist', to='streaming_music.artist')),
                ('album_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming_music.genre')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming_music.song')),
            ],
        ),
    ]
