# Generated by Django 3.2.16 on 2022-11-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='../static/image/spotiflix.jpg', upload_to='django-image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming_music.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('R', 'Rock'), ('J', 'Jazz'), ('P', 'Pop'), ('H', 'House'), ('B', 'Blues'), ('M', 'Metal')], max_length=10),
        ),
    ]
