# Generated by Django 3.2.16 on 2022-11-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='default', upload_to='django-image/'),
        ),
    ]
