# Generated by Django 3.2.16 on 2022-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0002_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='first_name_artist',
            field=models.CharField(max_length=50),
        ),
    ]
