# Generated by Django 3.2.16 on 2022-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0002_auto_20221111_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='../static/image/spotiflix.jpg', upload_to='django-image'),
        ),
    ]
