# Generated by Django 3.2.16 on 2022-10-22 18:30

import cloudinary.models
from django.db import migrations, models
import streaming_music.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0002_auto_20221022_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=streaming_music.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='song', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='album cover'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='other',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
