# Generated by Django 3.2.16 on 2022-11-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0003_alter_song_first_name_artist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
