# Generated by Django 3.2.16 on 2022-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0003_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='../static/image/spotiflix.jpg', upload_to='django-image/'),
        ),
    ]
