# Generated by Django 3.2.16 on 2022-10-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0003_auto_20221022_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['uploaded_on']},
        ),
        migrations.AddField(
            model_name='song',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
