# Generated by Django 3.2.16 on 2022-10-26 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaming_music', '0004_auto_20221026_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='album_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='song_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
