# Generated by Django 3.2.16 on 2022-11-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='approved',
        ),
    ]
