# Generated by Django 3.2.16 on 2022-11-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0008_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='track',
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
