# Generated by Django 3.2.16 on 2022-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0009_auto_20221117_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Pop', 'Pop'), ('House', 'House'), ('Blues', 'Blues'), ('Metal', 'Metal'), ('Other', 'Other')], default=None, max_length=5),
        ),
    ]
