# Generated by Django 3.2.16 on 2022-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_music', '0010_alter_album_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='first_name_artist',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='last_name_artist',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('first_name_artist', 'last_name_artist')},
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
